# PowerShell profile configuration
{
  config,
  lib,
  deploy,
  ...
}:
let
  esc = deploy.escapePowerShell;
  cfg = config.programs.powershell;
  profilePath = "%USERPROFILE%/Documents/PowerShell/Microsoft.PowerShell_profile.ps1";
  allHostsProfilePath = "%USERPROFILE%/Documents/PowerShell/profile.ps1";
in
{
  options.programs.powershell = {
    enable = lib.mkEnableOption "PowerShell profile";

    profileExtra = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra content for PowerShell profile script.";
    };

    initModules = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "PowerShell modules to import at startup.";
    };

    aliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "PowerShell aliases (name = command).";
    };

  };

  config = lib.mkIf cfg.enable (
    let
      env = config.environment;
      moduleLines = map (m: "Import-Module '${esc m}'") cfg.initModules;
      aliasLines = lib.mapAttrsToList (
        name: cmd: "Set-Alias -Name '${esc name}' -Value '${esc cmd}'"
      ) cfg.aliases;
    in
    lib.mkMerge [
      {
        windows.file.${profilePath}.text =
          lib.concatStringsSep "\n" (
            [ "# Generated by nix-windows" ]
            ++ lib.optional (env.shellInit != "") env.shellInit
            ++ lib.optional (env.loginShellInit != "") env.loginShellInit
            ++ moduleLines
            ++ aliasLines
            ++ lib.optional (cfg.profileExtra != "") cfg.profileExtra
          )
          + "\n";
      }
      (lib.mkIf (env.shellInit != "") {
        windows.file.${allHostsProfilePath}.text =
          "# Generated by nix-windows (environment.shellInit)\n" + env.shellInit + "\n";
      })
    ]
  );
}
