# Windows Registry management via PowerShell
{
  config,
  lib,
  deploy,
  dag,
  ...
}:
let

  psType = {
    string = "String";
    expandString = "ExpandString";
    multiString = "MultiString";
    dword = "DWord";
    qword = "QWord";
    binary = "Binary";
  };

  validTypes = builtins.attrNames psType;

  formatPsValue =
    entry:
    if builtins.isList entry.value then
      "@(${lib.concatMapStringsSep ", " (v: "'${deploy.escapePowerShell (toString v)}'") entry.value})"
    else if builtins.isInt entry.value then
      toString entry.value
    else
      "'${deploy.escapePowerShell (toString entry.value)}'";

  # Coerce a value to a registry entry, or null if it's a branch (nested path segment)
  coerceLeaf =
    v:
    if builtins.isInt v then
      {
        type = "dword";
        value = v;
      }
    else if builtins.isString v then
      {
        type = "string";
        value = v;
      }
    else if builtins.isList v then
      {
        type = "multiString";
        value = map toString v;
      }
    else if builtins.isAttrs v && v ? type && v ? value then
      if builtins.elem v.type validTypes then
        v
      else
        throw "system.registry: invalid type '${v.type}' (valid: ${lib.concatStringsSep ", " validTypes})"
    else
      null;

  # Recursively walk nested attrset, collecting { path, name, entry } triples
  collectEntries =
    prefix: tree:
    lib.concatLists (
      lib.mapAttrsToList (
        key: v:
        let
          leaf = coerceLeaf v;
          fullPath = if prefix == "" then key else "${prefix}\\${key}";
        in
        if leaf != null then
          [
            {
              path = prefix;
              name = key;
              entry = leaf;
            }
          ]
        else if builtins.isAttrs v then
          collectEntries fullPath v
        else
          throw "system.registry: invalid value at ${fullPath}"
      ) tree
    );

  allEntries = collectEntries "" config.system.registry;

  hiveOf =
    path:
    if path == "HKCU" || lib.hasPrefix "HKCU\\" path then
      "HKCU"
    else if path == "HKLM" || lib.hasPrefix "HKLM\\" path then
      "HKLM"
    else
      null;

  rootEntries = builtins.filter (e: e.path == "") allEntries;
  hkcuEntries = builtins.filter (e: hiveOf e.path == "HKCU") allEntries;
  hklmEntries = builtins.filter (e: hiveOf e.path == "HKLM") allEntries;
  unknownEntries = builtins.filter (e: e.path != "" && hiveOf e.path == null) allEntries;

  mkPathCommands =
    path: entries:
    let
      esc = deploy.escapePowerShell;
      ensurePath = "try { if (!(Test-Path 'Registry::${esc path}')) { New-Item -Path 'Registry::${esc path}' -Force | Out-Null } } catch { Write-Error \"Failed to create registry path '${esc path}': $_\"; throw }";
      setProps = lib.concatMapStringsSep "\n" (
        e:
        "try { Set-ItemProperty -Path 'Registry::${esc path}' -Name '${esc e.name}' -Value ${formatPsValue e.entry} -Type ${psType.${e.entry.type}} -Force } catch { Write-Error \"Failed to set '${esc e.name}' at '${esc path}': $_\"; throw }"
      ) entries;
    in
    ensurePath + "\n" + setProps;

  mkRegistryScript =
    entries:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList mkPathCommands (builtins.groupBy (e: e.path) entries)
    );

  countEntries = entries: toString (builtins.length entries);
in
{
  options.system.registry = lib.mkOption {
    type = lib.types.anything;
    default = { };
    description = ''
      Windows Registry entries to manage.
      Use nested attrsets for paths: system.registry.HKCU.Software.Microsoft...
      Leaf values: int -> REG_DWORD, string -> REG_SZ, list -> REG_MULTI_SZ,
      or { type, value } for full control (expandString, qword, binary).
      HKCU entries are applied during activation; HKLM entries generate an admin script.
    '';
  };

  config = {
    assertions =
      map (e: {
        assertion = false;
        message = "system.registry: value '${e.name}' set at root level (must be nested under HKCU or HKLM)";
      }) rootEntries
      ++ map (e: {
        assertion = false;
        message = "system.registry path '${e.path}' has unsupported hive prefix (use HKCU or HKLM)";
      }) unknownEntries;

    system.activationScripts.registry = lib.mkIf (hkcuEntries != [ ]) (
      dag.entryAfter [ "fonts" ] ''
        echo "[registry] Setting ${countEntries hkcuEntries} HKCU key(s)..."
        ${deploy.mkPowerShellExec (mkRegistryScript hkcuEntries)}
      ''
    );

    windows.file = lib.mkIf (hklmEntries != [ ]) {
      "%USERPROFILE%/.config/nix-windows/admin-registry.ps1" = {
        source = builtins.toFile "admin-registry.ps1" ''
          # Generated by nix-windows — run from elevated PowerShell
          #Requires -RunAsAdministrator
          ${mkRegistryScript hklmEntries}
        '';
      };
    };
  };
}
