# Windows service management (requires elevation)
{
  config,
  lib,
  deploy,
  ...
}:
let
  esc = deploy.escapePowerShell;
  servicesCfg = config.system.services;
  hasServices = servicesCfg != { };

  mkServiceCommand =
    name: svc:
    let
      escapedName = esc name;
      comment = lib.optionalString (svc.description != null) "# ${svc.description}\n";
      existenceCheck = ''
        $svc = Get-Service -Name '${escapedName}' -ErrorAction SilentlyContinue
        if (-not $svc) { Write-Error "Service '${escapedName}' not found"; exit 1 }
      '';
      ensureDeps = lib.concatMapStringsSep "\n" (
        dep:
        let
          escapedDep = esc dep;
        in
        ''
          $dep = Get-Service -Name '${escapedDep}' -ErrorAction SilentlyContinue
          if (-not $dep) { Write-Error "Dependency '${escapedDep}' for service '${escapedName}' not found"; exit 1 }
          if ($dep.Status -ne 'Running') { Start-Service -Name '${escapedDep}' -ErrorAction Stop }
        ''
      ) svc.dependsOn;
      setStartup = "Set-Service -Name '${escapedName}' -StartupType '${svc.startupType}' -ErrorAction Stop";
      stateCmd =
        if svc.state == "Running" then
          ''
            if ($svc.Status -ne 'Running') { Start-Service -Name '${escapedName}' -ErrorAction Stop }
          ''
        else if svc.state == "Stopped" then
          ''
            if ($svc.Status -ne 'Stopped') { Stop-Service -Name '${escapedName}' -Force -ErrorAction Stop }
          ''
        else
          "";
    in
    comment + existenceCheck + ensureDeps + setStartup + "\n" + stateCmd;

  script =
    let
      header = ''
        # Generated by nix-windows — run from elevated PowerShell
        #Requires -RunAsAdministrator
      '';
      body = lib.concatStringsSep "\n" (lib.mapAttrsToList mkServiceCommand servicesCfg);
    in
    header + body;
in
{
  options.system.services = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          startupType = lib.mkOption {
            type = lib.types.enum [
              "Automatic"
              "Manual"
              "Disabled"
              "AutomaticDelayedStart"
            ];
            description = "Service startup type.";
          };
          state = lib.mkOption {
            type = lib.types.nullOr (
              lib.types.enum [
                "Running"
                "Stopped"
              ]
            );
            default = null;
            description = "Desired service state (null = don't change).";
          };
          description = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Human-readable description of the service configuration.";
          };
          dependsOn = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [ ];
            description = "Service names that must be running before this service starts.";
          };
        };
      }
    );
    default = { };
    description = ''
      Windows services to manage. Generates an admin script that must be run
      from an elevated PowerShell.
    '';
  };

  config.windows.file = lib.mkIf hasServices {
    "%USERPROFILE%/.config/nix-windows/admin-services.ps1" = {
      source = builtins.toFile "admin-services.ps1" script;
    };
  };
}
