# Windows Task Scheduler management
# Generates an admin PowerShell script for scheduled task registration.
{
  config,
  lib,
  deploy,
  ...
}:
let
  esc = deploy.escapePowerShell;
  tasksCfg = config.windows.tasks;
  hasTasks = tasksCfg != { };

  scheduleToTrigger =
    name: sched:
    if sched.type == "daily" then
      "$trigger_${esc name} = New-ScheduledTaskTrigger -Daily -At '${esc sched.at}'"
    else if sched.type == "weekly" then
      "$trigger_${esc name} = New-ScheduledTaskTrigger -Weekly -DaysOfWeek ${lib.concatStringsSep "," (map esc sched.daysOfWeek)} -At '${esc sched.at}'"
    else if sched.type == "logon" then
      "$trigger_${esc name} = New-ScheduledTaskTrigger -AtLogOn"
    else if sched.type == "interval" then
      "$trigger_${esc name} = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes ${toString sched.intervalMinutes})"
    else
      builtins.throw "windows.tasks.${name}: unknown schedule type '${sched.type}'";

  mkTaskCommand =
    name: task:
    let
      escapedName = esc name;
      argsStr = lib.optionalString (task.arguments != null) " -Argument '${esc task.arguments}'";
      trigger = scheduleToTrigger name task.schedule;
      runAsStr =
        if task.runAs == "SYSTEM" then
          " -User 'SYSTEM' -RunLevel Highest"
        else
          " -RunLevel ${if task.elevated then "Highest" else "Limited"}";
      descStr = lib.optionalString (task.description != null) ''
        $settings_${escapedName} = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
      '';
    in
    ''
      # Task: ${name}
      ${lib.optionalString (task.description != null) "# ${task.description}"}
      ${trigger}
      $action_${escapedName} = New-ScheduledTaskAction -Execute '${esc task.executable}'${argsStr}
      ${descStr}
      $existing_${escapedName} = Get-ScheduledTask -TaskName '${escapedName}' -ErrorAction SilentlyContinue
      if ($existing_${escapedName}) {
        Set-ScheduledTask -TaskName '${escapedName}' -Trigger $trigger_${escapedName} -Action $action_${escapedName}${runAsStr} | Out-Null
        ${
          if task.enabled then
            "Enable-ScheduledTask -TaskName '${escapedName}' | Out-Null"
          else
            "Disable-ScheduledTask -TaskName '${escapedName}' | Out-Null"
        }
        Write-Host "  Updated task: ${name}"
      } else {
        Register-ScheduledTask -TaskName '${escapedName}' -Trigger $trigger_${escapedName} -Action $action_${escapedName}${runAsStr} -Force | Out-Null
        ${lib.optionalString (
          !task.enabled
        ) "Disable-ScheduledTask -TaskName '${escapedName}' | Out-Null"}
        Write-Host "  Registered task: ${name}"
      }
    '';

  script =
    let
      header = ''
        # Generated by nix-windows — run from elevated PowerShell
        #Requires -RunAsAdministrator
      '';
      body = lib.concatStringsSep "\n" (lib.mapAttrsToList mkTaskCommand tasksCfg);
    in
    header + body;

  scheduleSubmodule = lib.types.submodule {
    options = {
      type = lib.mkOption {
        type = lib.types.enum [
          "daily"
          "weekly"
          "logon"
          "interval"
        ];
        description = "Schedule trigger type.";
      };

      at = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "02:30AM";
        description = "Time of day for daily/weekly triggers.";
      };

      daysOfWeek = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [
          "Monday"
          "Wednesday"
          "Friday"
        ];
        description = "Days for weekly triggers.";
      };

      intervalMinutes = lib.mkOption {
        type = lib.types.nullOr lib.types.int;
        default = null;
        example = 30;
        description = "Repetition interval in minutes for interval triggers.";
      };
    };
  };
in
{
  options.windows.tasks = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          executable = lib.mkOption {
            type = lib.types.str;
            description = "Path to the executable to run.";
          };

          arguments = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Command-line arguments for the executable.";
          };

          schedule = lib.mkOption {
            type = scheduleSubmodule;
            description = "When to run the task.";
          };

          description = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Human-readable description of the task.";
          };

          runAs = lib.mkOption {
            type = lib.types.enum [
              "User"
              "SYSTEM"
            ];
            default = "User";
            description = "Account to run the task as.";
          };

          elevated = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Run with highest privileges (admin).";
          };

          enabled = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Whether the task is enabled after registration.";
          };
        };
      }
    );
    default = { };
    description = ''
      Windows scheduled tasks to manage.
      Generates an admin script that must be run from an elevated PowerShell.
    '';
  };

  config.windows.file = lib.mkIf hasTasks {
    "%USERPROFILE%/.config/nix-windows/admin-tasks.ps1" = {
      source = builtins.toFile "admin-tasks.ps1" script;
    };
  };
}
