# List of all builtin modules for test evaluation
# Kept in sync with flake.nix moduleSet
[
  ../modules/activation.nix
  ../modules/assertions.nix
  ../modules/base.nix
  ../modules/checks.nix
  ../modules/defaults.nix
  ../modules/environment.nix
  ../modules/registry.nix
  ../modules/services.nix
  ../modules/komorebi.nix
  ../modules/whkd.nix
  ../modules/windows-terminal.nix
  ../modules/kanata.nix
  ../modules/git.nix
  ../modules/vscode.nix
  ../modules/starship.nix
  ../modules/powershell.nix
  ../modules/tasks.nix
  ../modules/winget.nix
  ../modules/wsl.nix
  ../modules/ssh.nix
  ../modules/glazewm.nix
  ../modules/autohotkey.nix
  ../modules/flow-launcher.nix
  ../modules/wezterm.nix
  ../modules/alacritty.nix
  ../modules/espanso.nix
  ../modules/powertoys.nix
  ../modules/firefox.nix
  ../modules/nushell.nix
  ../modules/oh-my-posh.nix
  ../modules/fastfetch.nix
  ../modules/mpv.nix
  ../modules/rio.nix
]
